package v1beta1

// +kubebuilder:validation:Enum=Balanced_B0;Balanced_B1;Balanced_B3;Balanced_B5;Balanced_B10;Balanced_B20;Balanced_B50;Balanced_B100;Balanced_B150;Balanced_B250;Balanced_B350;Balanced_B500;Balanced_B700;Balanced_B1000;ComputeOptimized_X3;ComputeOptimized_X5;ComputeOptimized_X10;ComputeOptimized_X20;ComputeOptimized_X50;ComputeOptimized_X100;ComputeOptimized_X150;ComputeOptimized_X250;ComputeOptimized_X350;ComputeOptimized_X500;ComputeOptimized_X700;MemoryOptimized_M10;MemoryOptimized_M20;MemoryOptimized_M50;MemoryOptimized_M100;MemoryOptimized_M150;MemoryOptimized_M250;MemoryOptimized_M350;MemoryOptimized_M500;MemoryOptimized_M700;MemoryOptimized_M1000;MemoryOptimized_M1500;MemoryOptimized_M2000;FlashOptimized_A250;FlashOptimized_A500;FlashOptimized_A700;FlashOptimized_A1000;FlashOptimized_A1500;FlashOptimized_A2000;FlashOptimized_A4500;Enterprise_E1;Enterprise_E5;Enterprise_E10;Enterprise_E20;Enterprise_E50;Enterprise_E100;Enterprise_E200;Enterprise_E400;EnterpriseFlash_F300;EnterpriseFlash_F700;EnterpriseFlash_F1500
type AzureManagedRedisSKU string

const (
	AzureManagedRedisSKUBalancedB0    AzureManagedRedisSKU = "Balanced_B0"
	AzureManagedRedisSKUBalancedB1    AzureManagedRedisSKU = "Balanced_B1"
	AzureManagedRedisSKUBalancedB3    AzureManagedRedisSKU = "Balanced_B3"
	AzureManagedRedisSKUBalancedB5    AzureManagedRedisSKU = "Balanced_B5"
	AzureManagedRedisSKUBalancedB10   AzureManagedRedisSKU = "Balanced_B10"
	AzureManagedRedisSKUBalancedB20   AzureManagedRedisSKU = "Balanced_B20"
	AzureManagedRedisSKUBalancedB50   AzureManagedRedisSKU = "Balanced_B50"
	AzureManagedRedisSKUBalancedB100  AzureManagedRedisSKU = "Balanced_B100"
	AzureManagedRedisSKUBalancedB150  AzureManagedRedisSKU = "Balanced_B150"
	AzureManagedRedisSKUBalancedB250  AzureManagedRedisSKU = "Balanced_B250"
	AzureManagedRedisSKUBalancedB350  AzureManagedRedisSKU = "Balanced_B350"
	AzureManagedRedisSKUBalancedB500  AzureManagedRedisSKU = "Balanced_B500"
	AzureManagedRedisSKUBalancedB700  AzureManagedRedisSKU = "Balanced_B700"
	AzureManagedRedisSKUBalancedB1000 AzureManagedRedisSKU = "Balanced_B1000"

	AzureManagedRedisSKUComputeOptimizedX3   AzureManagedRedisSKU = "ComputeOptimized_X3"
	AzureManagedRedisSKUComputeOptimizedX5   AzureManagedRedisSKU = "ComputeOptimized_X5"
	AzureManagedRedisSKUComputeOptimizedX10  AzureManagedRedisSKU = "ComputeOptimized_X10"
	AzureManagedRedisSKUComputeOptimizedX20  AzureManagedRedisSKU = "ComputeOptimized_X20"
	AzureManagedRedisSKUComputeOptimizedX50  AzureManagedRedisSKU = "ComputeOptimized_X50"
	AzureManagedRedisSKUComputeOptimizedX100 AzureManagedRedisSKU = "ComputeOptimized_X100"
	AzureManagedRedisSKUComputeOptimizedX150 AzureManagedRedisSKU = "ComputeOptimized_X150"
	AzureManagedRedisSKUComputeOptimizedX250 AzureManagedRedisSKU = "ComputeOptimized_X250"
	AzureManagedRedisSKUComputeOptimizedX350 AzureManagedRedisSKU = "ComputeOptimized_X350"
	AzureManagedRedisSKUComputeOptimizedX500 AzureManagedRedisSKU = "ComputeOptimized_X500"
	AzureManagedRedisSKUComputeOptimizedX700 AzureManagedRedisSKU = "ComputeOptimized_X700"

	AzureManagedRedisSKUMemoryOptimizedM10   AzureManagedRedisSKU = "MemoryOptimized_M10"
	AzureManagedRedisSKUMemoryOptimizedM20   AzureManagedRedisSKU = "MemoryOptimized_M20"
	AzureManagedRedisSKUMemoryOptimizedM50   AzureManagedRedisSKU = "MemoryOptimized_M50"
	AzureManagedRedisSKUMemoryOptimizedM100  AzureManagedRedisSKU = "MemoryOptimized_M100"
	AzureManagedRedisSKUMemoryOptimizedM150  AzureManagedRedisSKU = "MemoryOptimized_M150"
	AzureManagedRedisSKUMemoryOptimizedM250  AzureManagedRedisSKU = "MemoryOptimized_M250"
	AzureManagedRedisSKUMemoryOptimizedM350  AzureManagedRedisSKU = "MemoryOptimized_M350"
	AzureManagedRedisSKUMemoryOptimizedM500  AzureManagedRedisSKU = "MemoryOptimized_M500"
	AzureManagedRedisSKUMemoryOptimizedM700  AzureManagedRedisSKU = "MemoryOptimized_M700"
	AzureManagedRedisSKUMemoryOptimizedM1000 AzureManagedRedisSKU = "MemoryOptimized_M1000"
	AzureManagedRedisSKUMemoryOptimizedM1500 AzureManagedRedisSKU = "MemoryOptimized_M1500"
	AzureManagedRedisSKUMemoryOptimizedM2000 AzureManagedRedisSKU = "MemoryOptimized_M2000"

	AzureManagedRedisSKUFlashOptimizedA250  AzureManagedRedisSKU = "FlashOptimized_A250"
	AzureManagedRedisSKUFlashOptimizedA500  AzureManagedRedisSKU = "FlashOptimized_A500"
	AzureManagedRedisSKUFlashOptimizedA700  AzureManagedRedisSKU = "FlashOptimized_A700"
	AzureManagedRedisSKUFlashOptimizedA1000 AzureManagedRedisSKU = "FlashOptimized_A1000"
	AzureManagedRedisSKUFlashOptimizedA1500 AzureManagedRedisSKU = "FlashOptimized_A1500"
	AzureManagedRedisSKUFlashOptimizedA2000 AzureManagedRedisSKU = "FlashOptimized_A2000"
	AzureManagedRedisSKUFlashOptimizedA4500 AzureManagedRedisSKU = "FlashOptimized_A4500"

	AzureManagedRedisSKUEnterpriseE1   AzureManagedRedisSKU = "Enterprise_E1"
	AzureManagedRedisSKUEnterpriseE5   AzureManagedRedisSKU = "Enterprise_E5"
	AzureManagedRedisSKUEnterpriseE10  AzureManagedRedisSKU = "Enterprise_E10"
	AzureManagedRedisSKUEnterpriseE20  AzureManagedRedisSKU = "Enterprise_E20"
	AzureManagedRedisSKUEnterpriseE50  AzureManagedRedisSKU = "Enterprise_E50"
	AzureManagedRedisSKUEnterpriseE100 AzureManagedRedisSKU = "Enterprise_E100"
	AzureManagedRedisSKUEnterpriseE200 AzureManagedRedisSKU = "Enterprise_E200"
	AzureManagedRedisSKUEnterpriseE400 AzureManagedRedisSKU = "Enterprise_E400"

	AzureManagedRedisSKUEnterpriseFlashF300  AzureManagedRedisSKU = "EnterpriseFlash_F300"
	AzureManagedRedisSKUEnterpriseFlashF700  AzureManagedRedisSKU = "EnterpriseFlash_F700"
	AzureManagedRedisSKUEnterpriseFlashF1500 AzureManagedRedisSKU = "EnterpriseFlash_F1500"
)
