apiVersion: cloud-control.kyma-project.io/v1beta1
kind: VpcPeering
metadata:
  name: vpcpeering-test
  namespace: kcp-system
spec:
  vpcPeering:
    gcp:
      remotePeeringName: vpcpeering-sap-gcp-skr-dev-cust-00002-sap-sc-learn
      remoteProject: sap-sc-learn
      remoteVpc: default
      importCustomRoutes: false
  scope:
    name: 57bc9639-d752-4f67-8b9e-7cd12514575f
  remoteRef:
    name: vpcpeering-test
    namespace: kube-public