apiVersion: v1
data:
  details: |-
    body:
      - name: configuration
        widget: Panel
        source: spec
        children:
          - name: spec.shardCount
            source: shardCount
            widget: Labels
          - name: spec.redisVersion
            source: redisVersion
            widget: Labels
          - name: spec.redisTier
            source: redisTier
            widget: Labels


      - name: spec.redisConfiguration
        widget: Panel
        source: spec.redisConfiguration
        children:
          - name: spec.redisConfiguration.maxclients
            source: maxclients
            widget: Labels
          - name: spec.redisConfiguration.maxfragmentationmemory-reserved
            source: maxfragmentationmemory-reserved
            widget: Labels
          - name: spec.redisConfiguration.maxmemory-delta
            source: maxmemory-delta
            widget: Labels
          - name: spec.redisConfiguration.maxmemory-policy
            source: maxmemory-policy
            widget: Labels
          - name: spec.redisConfiguration.maxmemory-reserved
            source: maxmemory-reserved
            widget: Labels
          - name: spec.redisConfiguration.notify-keyspace-events
            source: notify-keyspace-events
            widget: Labels

      - name: spec.volume
        widget: Panel
        source: spec.volume
        children:
          - name: spec.volume.name
            source: name
            widget: Labels
          - name: spec.volume.labels
            source: labels
            widget: Labels
          - name: spec.volume.annotations
            source: annotations
            widget: Labels

      - name: spec.ipRange
        widget: Panel
        source: spec.ipRange
        children:
          - name: spec.ipRange.name
            source: name
            widget: Labels

      - name: status
        widget: Panel
        source: status
        children:
          - name: status.state
            source: state
            widget: Labels
  form: |2

    - path: spec.shardCount
      name: spec.shardCount
      required: false
      disableOnEdit: true
    - path: spec.redisVersion
      name: spec.redisVersion
      required: false
      disableOnEdit: true

    - path: spec.redisTier
      name: spec.redisTier
      required: true
      disableOnEdit: false

    - path: spec.redisConfiguration
      name: spec.redisConfiguration
      required: false
      widget: FormGroup
      children:
        - path: maxclients
          name: spec.redisConfiguration.maxclients
          disableOnEdit: true
        - path: maxfragmentationmemory-reserved
          name: spec.redisConfiguration.maxfragmentationmemory-reserved
          disableOnEdit: true
        - path: maxmemory-delta
          name: spec.redisConfiguration.maxmemory-delta
          disableOnEdit: true
        - path: maxmemory-policy
          name: spec.redisConfiguration.maxmemory-policy
          disableOnEdit: true
        - path: maxmemory-reserved
          name: spec.redisConfiguration.maxmemory-reserved
          disableOnEdit: true
        - path: notify-keyspace-events
          name: spec.redisConfiguration.notify-keyspace-events
          disableOnEdit: true

    - path: spec.volume
      name: spec.volume
      required: false
      widget: FormGroup
      children:
        - path: name
          name: spec.volume.name
        - path: labels
          name: spec.volume.labels
          widget: KeyValuePair
        - path: annotations
          name: spec.volume.annotations
          widget: KeyValuePair

    - path: spec.ipRange
      name: spec.ipRange
      required: true
      widget: FormGroup
      children:
        - path: name
          name: spec.ipRange.name
          required: true
  general: |
    resource:
        kind: AzureRedisInstance
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: azureredisinstances
    name: Azure Redis Instances
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        AzureRedisInstance description here
  list: |
    - source: status.state
      name: status.state
      sort: true
  translations: |-
    en:
      configuration: Configuration
      status: Status
      status.state: State
      spec.enableNonSslPort: Enable Non SSL Port
      spec.shardCount: Shard Count
      spec.redisVersion: Redis Version
      spec.redisTier: Redis Tier
      spec.sku.capacity: Capacity
      spec.redisConfiguration: Redis Configuration
      spec.redisConfiguration.maxclients: Max Clients
      spec.redisConfiguration.maxfragmentationmemory-reserved: Max Fragmentation Memory Reserved
      spec.redisConfiguration.maxmemory-delta: Max Memory Delta
      spec.redisConfiguration.maxmemory-policy: Max Memory Policy
      spec.redisConfiguration.maxmemory-reserved: Max Memory Reserved
      spec.redisConfiguration.notify-keyspace-events: Notify Keyspace Events
      spec.redisConfiguration.zonal-configuration: Zonal Configuration
      spec.volume: Volume
      spec.volume.name: Name
      spec.volume.labels: Labels
      spec.volume.annotations: Annotations
      spec.ipRange: IP Range
      spec.ipRange.name: Name
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.7
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: azureredisinstances-ui.operator.kyma-project.io
  namespace: kyma-system
