sonar.projectKey=kyma-project-cloud-manager
sonar.projectName=Kyma Project Cloud Manager

sonar.sources=.
sonar.exclusions=**/*_test.go,tmp/**,tools/**,config/default/**,config/manager/**,config/rbac/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

