package v1beta1

const (
	ConditionTypeError                     = "Error"
	ConditionTypeReady                     = "Ready"
	ConditionTypeWarning                   = "Warning"
	ConditionTypeUpdating                  = "Updating"
	ConditionTypeSubscription              = "Subscription"
	ConditionTypeInfrastructureProvisioned = "InfrastructureProvisioned"
	ConditionTypeDeleteWhileUsed           = "DeleteWhileUsed"
	ConditionTypeDeleting                  = "Deleting"

	ReasonScopeNotFound       = "ScopeNoFound"
	ReasonProcessing          = "Processing"
	ReasonInvalidSpec         = "InvalidSpec"
	ReasonUnknown             = "Unknown"
	ReasonNotFound            = "NotFound"
	ReasonReady               = "Ready"
	ReasonGcpError            = "GCPError"
	ReasonValidationFailed    = "ValidationFailed"
	ReasonMissingDependency   = "MissingDependency"
	ReasonWaitingDependency   = "WaitingDependency"
	ReasonDeleteWhileUsed     = "DeleteWhileUsed"
	ReasonCloudProviderError  = "CloudProviderError"
	ReasonProvisioned         = "Provisioned"
	ReasonInvalidCidr         = "InvalidCidr"
	ReasonCidrOverlap         = "CidrOverlap"
	ReasonInvalidSubscription = "InvalidSubscription"
	ReasonInvalidBinding      = "InvalidBinding"
	ReasonProviderError       = "ProviderError"
	ReasonDeleting            = "Deleting"
)
