apiVersion: v1
data:
  details: ""
  form: ""
  general: |-
    resource:
        kind: GcpSubnet
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: gcpsubnets
    name: GCP Subnets
    scope: cluster
    category: Discovery and Network
    icon: tnt/network
    description: >-
        Description here
  list: ""
  translations: ""
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.1
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: gcpsubnets-ui.operator.kyma-project.io
  namespace: kyma-system
