apiVersion: v1
data:
  details: |+
    body:
      - name: spec.pvcRef
        widget: Panel
        source: spec.pvcRef
        children:
          - widget: Labels
            source: apiVersion
            name: spec.pvcRef.apiVersion
          - widget: Labels
            source: kind
            name: spec.pvcRef.kind
          - widget: Labels
            source: name
            name: spec.pvcRef.name
          - widget: Labels
            source: namespace
            name: spec.pvcRef.namespace

      - name: configuration
        widget: Panel
        source: spec
        children:
          - widget: Labels
            source: schedule
            name: spec.schedule
          - widget: Labels
            source: startTime
            name: spec.startTime
          - widget: Labels
            source: endTime
            name: spec.endTime
          - widget: Labels
            source: prefix
            name: spec.prefix
          - widget: Labels
            source: maxRetentionDays
            name: spec.maxRetentionDays
          - widget: Labels
            source: maxReadyBackups
            name: spec.maxReadyBackups
          - widget: Labels
            source: maxFailedBackups
            name: spec.maxFailedBackups
          - widget: Labels
            source: deleteCascade
            name: spec.deleteCascade
          - widget: Labels
            source: suspend
            name: spec.suspend


      - name: status
        widget: Panel
        source: status
        children:
          - name: status.state
            source: state
            widget: Labels

  form: |
    - path: spec.pvcRef
      name: spec.pvcRef
      required: true
      widget: FormGroup
      children:
        - path: apiVersion
          name: spec.pvcRef.apiVersion
          required: true
        - path: kind
          name: spec.pvcRef.kind
          required: true
        - path: name
          name: spec.pvcRef.name
          required: true
        - path: namespace
          name: spec.pvcRef.namespace
          required: true

    - path: spec.schedule
      name: spec.schedule
      required: false
    - path: spec.startTime
      name: spec.startTime
      required: false
    - path: spec.endTime
      name: spec.endTime
      required: false
    - path: spec.prefix
      name: spec.prefix
      required: false
    - path: spec.maxRetentionDays
      name: spec.maxRetentionDays
      required: false
    - path: spec.maxReadyBackups
      name: spec.maxReadyBackups
      required: false
    - path: spec.maxFailedBackups
      name: spec.maxFailedBackups
      required: false
    - path: spec.deleteCascade
      name: spec.deleteCascade
      required: false
    - path: spec.suspend
      name: spec.suspend
      required: false
  general: |-
    resource:
        kind: AzureRwxBackupSchedule
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: azurerwxbackupschedules
    name: Azure RWX Backup Schedules
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        Azure RWX Backup Schedules description here
  list: |-
    - source: spec.schedule
      name: spec.schedule
      sort: true
    - source: status.lastCreateRun
      name: status.lastCreateRun
      sort: true
    - source: status.state
      name: status.state
      sort: true
  translations: |-
    en:
      configuration: Configuration
      status: Status
      spec.schedule: Schedule
      spec.startTime: Start Time
      spec.endTime: End Time
      spec.prefix: Prefix
      spec.maxRetentionDays: Max Retention Days
      spec.maxReadyBackups: Max Backups in Ready State
      spec.maxFailedBackups: Max Backups in Failed State
      spec.deleteCascade: Delete Cascade
      spec.suspend: Suspend
      status.lastCreateRun: Last Run Time
      status.state: State
      spec.pvcRef: Persistent Volume Claim
      spec.pvcRef.apiVersion: API Version
      spec.pvcRef.kind: Kind
      spec.pvcRef.name: Name
      spec.pvcRef.namespace: Namespace
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.1
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: azurerwxbackupschedules-ui.operator.kyma-project.io
  namespace: kyma-system
