# permissions for end users to view awsredisclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: cloud-resources-awsrediscluster-viewer-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsredisclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsredisclusters/status
  verbs:
  - get
