# permissions for end users to edit redisclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: cloud-control-rediscluster-editor-role
rules:
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - redisclusters/status
  verbs:
  - get
