# permissions for end users to edit gcpsubnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: cloud-resources-gcpsubnet-editor-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpsubnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpsubnets/status
  verbs:
  - get
