# This rule is not used by the project cloud-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cloud-control.kyma-project.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: cloud-control-skrstatus-viewer-role
rules:
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - skrstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - skrstatuses/status
  verbs:
  - get
