apiVersion: cloud-control.kyma-project.io/v1beta1
kind: VpcPeering
metadata:
  labels:
    app.kubernetes.io/name: vpcpeering
    app.kubernetes.io/instance: vpcpeering-sample
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-manager
  name: vpcpeering-sample
spec:
  scopeRef:
    name: phx-azr-02
  remoteRef:
    namespace: skr-namespace
    name: skr-vpcpeering-sample
  vpcPeering:
    azure:
      remoteResourceGroup: MyResourceGroup
      remoteVnet: /subscriptions/e492e533-1d28-4dde-85f7-0399ec55565f/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualNetworks/MyVnet
