apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: GcpRedisInstance
metadata:
  labels:
    app.kubernetes.io/name: gcpredisinstance
    app.kubernetes.io/instance: gcpredisinstance-sample
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-manager
  name: gcpredisinstance-sample
spec:
  # required fields
  memorySizeGb: 1
  tier: "BASIC"

  # optional fields
  redisVersion: REDIS_7_0
  authEnabled: true
  transitEncryptionMode: SERVER_AUTHENTICATION
  redisConfigs:
    maxmemory-policy: volatile-lru
    activedefrag: "yes"
  maintenancePolicy:
    dayOfWeek:
      day: "TUESDAY"
      startTime:
          hours: 15
          minutes: 45