apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AwsRedisInstance
metadata:
  labels:
    app.kubernetes.io/name: awsredisinstance
    app.kubernetes.io/instance: awsredisinstance-sample
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-manager
  name: awsredisinstance-sample
spec:
  # required fields
  redisTier: "P1"

  # optional fields
  engineVersion: "7.0"
  autoMinorVersionUpgrade: true
  parameters:
    maxmemory-policy: volatile-lru
    activedefrag: "yes"
  preferredMaintenanceWindow: sun:23:00-mon:01:30

