apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureManagedRedisInstance
metadata:
  labels:
    app.kubernetes.io/name: azuremanagedredisinstance
    app.kubernetes.io/instance: azuremanagedredisinstance-sample
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-manager
  name: azuremanagedredisinstance-sample
spec:
  redisTier: P3
