apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureRwxBackupSchedule
metadata:
  labels:
    app.kubernetes.io/name: azurerwxbackupschedule
    app.kubernetes.io/instance: azurerwxbackupschedule-sample
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-manager
  name: azurerwxbackupschedule-sample
spec:
  # TODO(user): Add fields here
