apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureManagedRedisCluster
metadata:
  labels:
    app.kubernetes.io/name: azuremanagedrediscluster
    app.kubernetes.io/instance: azuremanagedrediscluster-sample
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-manager
  name: azuremanagedrediscluster-sample
spec:
  redisTier: C5
