apiVersion: cloud-control.kyma-project.io/v1beta1
kind: IpRange
spec:
  remoteRef:
    name: name
    namespace: ns
  scope:
    name: scope
---
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: Network
spec:
  network:
    reference:
      gcp:
        gcpProject: project-abcde-1234
        networkName: some-network
  scope:
    name: scope
---
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: NfsInstance
spec:
  ipRange:
    name: some-ip-range
  instance:
    aws:
      performanceMode: generalPurpose
      throughput: bursting
  remoteRef:
    name: name
    namespace: ns
  scope:
    name: scope
---
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: Nuke
spec:
  scope:
    name: scope
---
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: RedisInstance
spec:
  instance:
    gcp:
      memorySizeGb: 10
      tier: BASIC
  ipRange:
    name: iprange1
  remoteRef:
    name: name
    namespace: ns
  scope:
    name: scope
---
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: Scope
spec:
  kymaName: kyma
  provider: gcp
  region: us-east1
  scope:
    gcp:
      project: project-abcde-123
      vpcNetwork: vpcnetwork-123
  shootName: shot123
---
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: SkrStatus
spec:
  brokerPlan: plan
  globalAccount: gacc
  kymaName: kyma
  provider: gcp
  region: us-east1
  shootName: shoot123
  subAccount: subacc567
---
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: VpcPeering
spec:
  remoteRef:
    name: name
    namespace: ns
  scope:
    name: scope
  details:
    localNetwork:
      name: local-net
    remoteNetwork:
      name: remote-net
---
apiVersion: operator.kyma-project.io/v1beta2
kind: Kyma
