apiVersion: v1
data:
  details: ""
  form: ""
  general: |-
    resource:
        kind: AwsNfsBackupSchedule
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: awsnfsbackupschedules
    name: AWS NFS Backup Schedules
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        AWS NFS Backup Schedules description here
  list: ""
  translations: ""
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.1
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: awsnfsbackupschedules-ui.operator.kyma-project.io
  namespace: kyma-system
