name: Cloud-Manager Build Image PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
    paths-ignore:
      - .github/workflows/stale.yaml
      - docs/**

jobs:
  approve-image-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'pr-build-image') }}
    environment: e2e
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build approved"

  build-image:
    permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read # This is required for actions/checkout
    needs: approve-image-build
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: cloud-manager
      dockerfile: Dockerfile
      export-tags: true

  local-build:
    name: Build Image Locally
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'pr-build-image') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Image Locally
        uses: docker/build-push-action@v7
        with:
          context: .
          outputs: type=cacheonly
          push: false
          tags: user/app:latest
