name: PR Test
run-name: Test ${{ github.event.pull_request.number || github.ref_name }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
env:
  PIPELINE: true
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Build & Test GA
            variant: GA
            ffFile: pkg/feature/ff_ga.yaml
          - name: Build & Test Edge
            variant: Edge
            ffFile: pkg/feature/ff_edge.yaml
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'
      - name: Display Go version
        run: go version
      - name: Prepare ff config
        run: |
          mkdir -p tmp
          yq 'del(.apiDisabled)' ${{ matrix.ffFile }} > tmp/ff.yaml
      - name: Build and test
        env:
          FEATURE_FLAG_CONFIG_FILE: ${{ github.workspace }}/tmp/ff.yaml
        run: |
          ./config/sync.sh
          ./docs/contributor/permissions/sort.sh
          go mod tidy
          go mod download
          make build
          make test
      - name: Upload coverage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage-${{ matrix.variant }}.out
          path: cover.out
      - name: Check modified files
        run: git diff --exit-code
      - name: Check if test GUIDs are unique
        run: x=$(grep -rEho '[[:xdigit:]]{8}(-[[:xdigit:]]{4}){3}-[[:xdigit:]]{12}'  ./internal | sort | uniq -d); [ -z "${x}" ] || ( echo duplicated GUID detected $x; exit 1; )
